### ISSUE TITLE
[feature request] PDF detection

### ISSUE THREAD

**Issue by kaliiiiiiiiii** [kaliiiiiiiiii/brotector#5]
```js
var script = document.createElement('script');
script.src =
  'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
script.onload = function () {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();
  doc.text('test', 10, 20);
  const pdfURL = URL.createObjectURL(doc.output('blob'));
  const iframe = document.createElement('iframe');
  iframe.src = pdfURL;
  document.body.appendChild(iframe);
  iframe.onload = () => console.log(iframe.contentDocument.querySelector('style')?.textContent||'nothing');

};
document.head.appendChild(script)
```

```css
      body {
        height: 100%;
        width: 100%;
        overflow: hidden;
        margin: 0;
        background-color: rgb(38, 38, 38);
      }
```

Discovered by @anonymous, thanks a lot!
